<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body><table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="thwecmf_template_wrapper"><tr><td align="center" class="thwecmf-template-wrapper-column" valign="top" style="background-color: #f7f7f7; padding: 70px 0;"><table id="tpf_t_builder" width="600" cellspacing="0" cellpadding="0" class="thwecmf-main-builder thwecmf-template-block" style="max-width: 600px; width: 600px; margin: auto;"><tr><td class="thwecmf-builder-column" style="vertical-align: top; border-radius: 2px; background-size: cover; background-repeat: no-repeat; background-position: top; border-style: solid; border-color: #dedede; background-color: #ffffff; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px;">
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1001" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; background-size: 100%; background-repeat: no-repeat; background-position: top; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1002" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; padding-top: 36px; padding-right: 48px; padding-bottom: 36px; padding-left: 48px; text-align: center; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: #f3af46;"><table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1003" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #ffffff; font-size: 30px; line-height: 150%; font-weight: normal; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;"><tr style="color: #ffffff; font-size: 30px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #ffffff; font-size: 30px; font-weight: normal; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;">
			<div class="wecmf-txt-wrap" style="color: #ffffff; font-size: 30px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Order Failed: #<?php if(isset($order)) : ?><?php echo $order->get_id();?><?php endif; ?><br style="color: #ffffff; font-size: 30px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr></table></td></tr></table>
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1004" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; background-size: 100%; background-repeat: no-repeat; background-position: top; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1005" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; padding-top: 48px; padding-right: 48px; padding-bottom: 0px; padding-left: 48px; text-align: left; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;">
<table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1006" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 14px; line-height: 150%; font-weight: normal; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;"><tr style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 0px; padding-right: 0px; padding-bottom: 15px; padding-left: 0px;">
			<div class="wecmf-txt-wrap" style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Bonjour <?php if(isset($order)) : ?><?php echo esc_html($order->get_billing_first_name()); ?><?php elseif(isset($user_login)): ?><?php echo esc_html($user_login); ?><?php endif; ?>,<br style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
<div class="wecmf-txt-wrap" style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;"><br style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;"></div>
<div class="wecmf-txt-wrap" style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Le paiement de la commande #<?php if(isset($order)) : ?><?php echo $order->get_id();?><?php endif; ?> de <?php if(isset($order)) : ?><?php echo esc_html( $order->get_billing_first_name().' '.$order->get_billing_last_name() ); ?><?php elseif(isset($user_login)): ?><?php echo esc_html($user_login); ?><?php endif; ?> a échoué. La commande était la suivante :<br style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr></table>
<div class="thwecmf-hook-order-details"><?php if(isset($order)){ 
 					do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email ); 
 				}?></div>
<?php if(isset($order)){ 
  					do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email ); 
  				}?>
<?php if(isset($order)){ 
  					do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email ); 
  				}?>
<table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1010" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 14px; line-height: 150%; font-weight: normal; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;"><tr style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 15px; padding-right: 0px; padding-bottom: 15px; padding-left: 0px;">
			<div class="wecmf-txt-wrap" style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Veuillez réessayer ou vous rendre en agence<br style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr></table>
</td></tr></table>
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1014" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; background-size: 100%; background-repeat: no-repeat; background-position: top; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; border-style: dotted; border-color: #dddddd; padding-top: 12px; padding-right: 10px; padding-bottom: 12px; padding-left: 10px;"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1015" style="vertical-align: top; box-sizing: border-box; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; border-style: dotted; border-color: #dddddd; word-break: break-word; padding: 10px 10px; text-align: center; background-size: 100%; background-position: top;"><table class="thwecmf-block thwecmf-block-image thwecmf-builder-block" id="tpf_1018" cellspacing="0" cellpadding="0" align="center" style="table-layout: fixed; width: 100%; height: auto; max-width: 600px; box-sizing: border-box;"><tr><td class="thwecmf-block-child thwecmf-image-column" style="padding: 0; box-sizing: border-box; text-align: center; vertical-align: middle; line-height: 0;"><p style="padding: 10px 0px; margin: 0; width: 50%; display: inline-block; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent;">
			<img src="https://buscongo.shid.fr/wp-content/uploads/2022/01/cropped-bb-removebg-preview-2.png" alt="Image" width="277" height="78.4688" style="width: 100%; height: auto; max-width: 100%; max-height: 100%; display: block;"></p></td></tr></table></td></tr></table>
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1016" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; background-size: 100%; background-repeat: no-repeat; background-position: top; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; border-style: dotted; border-color: #dddddd; padding-top: 12px; padding-right: 10px; padding-bottom: 12px; padding-left: 10px;"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1017" style="vertical-align: top; box-sizing: border-box; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; border-style: dotted; border-color: #dddddd; word-break: break-word; padding: 10px 10px; text-align: center; background-size: 100%; background-position: top;"><table class="thwecmf-block thwecmf-block-social thwecmf-builder-block" id="tpf_1019" cellspacing="0" cellpadding="0" style="table-layout: fixed; text-align: center; width: 100%; box-sizing: border-box; background-size: cover; background-repeat: no-repeat; background-color: transparent; margin: 0 auto; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent;"><tr><td class="thwecmf-block-child thwecmf-social-outer-td" align="center" style="padding: 0; vertical-align: top; box-sizing: border-box; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;">
				<table class="thwecmf-social-inner-tb" cellspacing="0" cellpadding="0"><tr>
<td class="thwecmf-social-td thwecmf-td-fb" style="vertical-align: top; box-sizing: border-box; padding: 15px 3px 15px 3px; font-size: 0; line-height: 1px;">
			<p class="thwecmf-social-icon" style="width: 40px; height: 40px; margin: 0px; text-decoration: none; box-shadow: none;">
				<a href="http://www.facebook.com/" class="facebook" style="color: #1155cc; text-decoration: underline;">
					<img src="https://buscongo.shid.fr/wp-content/plugins/email-customizer-for-woocommerce/assets/images/facebook.png" alt="Facebook Icon" width="40" height="40" style="width: 100%; height: 100%; display: block; max-width: 100%; max-height: 100%;"></a>
			</p>
		</td>
<td class="thwecmf-social-td thwecmf-td-mail" style="vertical-align: top; box-sizing: border-box; padding: 15px 3px 15px 3px; font-size: 0; line-height: 1px;">
			<p class="thwecmf-social-icon" style="width: 40px; height: 40px; margin: 0px; text-decoration: none; box-shadow: none;">
				<a href="https://mail.google.com/mail/?view=cm&to=yourmail@example.com&bcc=somemail@example.com" class="mail" style="color: #1155cc; text-decoration: underline;">
					<img src="https://buscongo.shid.fr/wp-content/plugins/email-customizer-for-woocommerce/assets/images/email.png" alt="Google Icon" width="40" height="40" style="width: 100%; height: 100%; display: block; max-width: 100%; max-height: 100%;"></a>
			</p>
		</td>
<td class="thwecmf-social-td thwecmf-td-tw" style="vertical-align: top; box-sizing: border-box; padding: 15px 3px 15px 3px; font-size: 0; line-height: 1px;">	
			<p class="thwecmf-social-icon" style="width: 40px; height: 40px; margin: 0px; text-decoration: none; box-shadow: none;">
				<a href="http://www.twitter.com/" class="twitter" style="color: #1155cc; text-decoration: underline;">
					<img src="https://buscongo.shid.fr/wp-content/plugins/email-customizer-for-woocommerce/assets/images/twitter.png" alt="Twitter Icon" width="40" height="40" style="width: 100%; height: 100%; display: block; max-width: 100%; max-height: 100%;"></a>
			</p>
		</td>
<td class="thwecmf-social-td thwecmf-td-yb" style="vertical-align: top; box-sizing: border-box; padding: 15px 3px 15px 3px; font-size: 0; line-height: 1px;">
			<p class="thwecmf-social-icon" style="width: 40px; height: 40px; margin: 0px; text-decoration: none; box-shadow: none;">
				<a href="http://www.youtube.com/" class="youtube" style="color: #1155cc; text-decoration: underline;">
					<img src="https://buscongo.shid.fr/wp-content/plugins/email-customizer-for-woocommerce/assets/images/youtube.png" alt="Youtube Icon" width="40" height="40" style="width: 100%; height: 100%; display: block; max-width: 100%; max-height: 100%;"></a>
			</p>
		</td>
<td class="thwecmf-social-td thwecmf-td-lin" style="vertical-align: top; box-sizing: border-box; padding: 15px 3px 15px 3px; font-size: 0; line-height: 1px;">
			<p class="thwecmf-social-icon" style="width: 40px; height: 40px; margin: 0px; text-decoration: none; box-shadow: none;">
				<a href="https://www.linkedin.com/" class="linkedin" style="color: #1155cc; text-decoration: underline;">
					<img src="https://buscongo.shid.fr/wp-content/plugins/email-customizer-for-woocommerce/assets/images/linkedin.png" alt="Linkedin Icon" width="40" height="40" style="width: 100%; height: 100%; display: block; max-width: 100%; max-height: 100%;"></a>
			</p>
		</td>
<td class="thwecmf-social-td thwecmf-td-pin" style="vertical-align: top; box-sizing: border-box; padding: 15px 3px 15px 3px; font-size: 0; line-height: 1px;">
			<p class="thwecmf-social-icon" style="width: 40px; height: 40px; margin: 0px; text-decoration: none; box-shadow: none;">
				<a href="http://www.pinterest.com/" class="pinterest" style="color: #1155cc; text-decoration: underline;">
					<img src="https://buscongo.shid.fr/wp-content/plugins/email-customizer-for-woocommerce/assets/images/pinterest.png" alt="Pinterest Icon" width="40" height="40" style="width: 100%; height: 100%; display: block; max-width: 100%; max-height: 100%;"></a>
			</p>
		</td>
<td class="thwecmf-social-td thwecmf-td-insta" style="vertical-align: top; box-sizing: border-box; padding: 15px 3px 15px 3px; font-size: 0; line-height: 1px;">
	  		<p class="thwecmf-social-icon" style="width: 40px; height: 40px; margin: 0px; text-decoration: none; box-shadow: none;">
	  			<a href="http://www.instagram.com/" class="instagram" style="color: #1155cc; text-decoration: underline;">
	    			<img src="https://buscongo.shid.fr/wp-content/plugins/email-customizer-for-woocommerce/assets/images/instagram.png" alt="Instagram Icon" width="40" height="40" style="width: 100%; height: 100%; display: block; max-width: 100%; max-height: 100%;"></a>
	  		</p>
	  	</td>
</tr></table>
</td></tr></table></td></tr></table>
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1011" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; background-size: 100%; background-repeat: no-repeat; background-position: top; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1012" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; padding-top: 0px; padding-right: 48px; padding-bottom: 48px; padding-left: 48px; text-align: center; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;"></td></tr></table>
</td></tr></table></td></tr></table></body>
</html>
